### ISSUE TITLE
Reclustering when panning?

### ISSUE THREAD

**Issue by MarcBate** [nickcam/FlareClusterLayer#11]
Just wondering why it reclusters when you pan the map and all of the data is in the extent before and after the pan?

Btw, I think this is amazing and I plan on implementing it in our application.

**Comment by nickcam** [comment]
Thanks @MarcBate.
It recalculates on every movement of the map (including pans) as the clustering works by dividing the visible extent into equal sized blocks (the cluster grid) and clustering the points that are in those blocks if its needed. This means even on a pan it needs to recreate the cluster grid and therefore also recluster the points.

Could potentially have a check when performing the clustering that if clusters already exist and all data points were previously within the old extent and are also within the new extent then don't do anything. Would need some extra flags and some more logic....sounds simple enough, but the catch will be checking whether all points are still within the new extent as well. I think it would involve looping all points (at least until one is found outside of the new extent) before doing the clustering - an extra loop will slow things down depending on the size of the data set, so hesitant to do it.

Its a good suggestion worth looking at though, will leave this open and have a look when time permits.

**Comment by MarcBate** [comment]
I've added a few options to the v3 flare cluster layer, none of which are used by default, including this check for pans with the cluster areas contained within the new extent, allowing the data source to be an array of Graphics objects, allowing for an array of graphics objects to be added or removed from the cluster layer, passing a UV renderer for the singles renderer, changing hover/always without recreating the layer, option to set the flare fill/outline color to that of the area renderer.

It is working great even with over 50,000 points. Thanks for your work on this.

Honestly, I've only ever taken from github, and not sure how to contribute. Do I just check in changes and then you decide whether to merge them?

**Comment by nickcam** [comment]
Ok cool. Thanks!
To contribute: Fork the repository. Make the updates in the forked version, then commit them to your forked version. From there you create a pull request back to this repo where I can review the changes and commit them to this repo.

That's a bad explanation :). This does it better - see the section on Pull Requests.
[https://guides.github.com/activities/contributing-to-open-source/](https://guides.github.com/activities/contributing-to-open-source/)

**Comment by MarcBate** [comment]
Thanks for the info. Btw, here's a couple screenshots.
http://bit.ly/2dIeMJ2
http://bit.ly/2e6gx28

**Comment by DOOMitru** [comment]
Hi @MarcBate, I would be interested in using some of the options you say you've added to Nick's FCL v3.  Unfortunately the bitly links you've posted are not accessible.  Is there a way I could get a copy of the FCL with your changes?

**Comment by nickcam** [comment]
Hi @MarcBate, how'd you go with those updates - still keen to review and merge them if you can create a pull request?
