### ISSUE TITLE
Load new data on button click

### ISSUE THREAD

**Issue by DOOMitru** [nickcam/FlareClusterLayer#12]
Hi Nick,

I would really like to use your FlareClusterLayer_V3 in an application that I'm working on but I'm not very familiar with Dojo modules and how exactly they work.  I've been trying to figure out a way to load new data into the map and re-cluster it on a button click event but I could only get it to work for the first click.  On subsequent clicks, I get an error in the console saying "this.map is undefined".

This is basically what I've tried doing without success:

```
on(dom.byId('theButton'), 'click', function(){
   esriRequest({
        url: "data.json",
        handleAs: "json"
    })
    .then(function(resp) {
        formatData(resp);
    })
    .then(function() {
        initLayer();
    }); 
});
```

Ideally I would like to have a function I could call on a button click and pass it a URL where to get the data from and then re-cluster and re-load the new data on the map, ie (vanilla js): 

```
document.getElementById("btn").addEventListener("click", function(){
    Fn('data.json');
});
```

I would appreciate your help.

Thanks,
DOOMitru

**Comment by nickcam** [comment]
Hi @DOOMitru, no worries - I've just created this plunker that shows how to do it.
[https://plnkr.co/edit/9o5CFWuYfUpgRBpLbO2z](https://plnkr.co/edit/9o5CFWuYfUpgRBpLbO2z)

Just keep hitting the Reload data button and it will reload the data each time, in the example it's the same data all the time.

Essentially you just setup the map and cluster layer first, in this case inside of a dojo/domReady function - same sort of deal as jQuery's `$(function(){ })`. Assign a click event and inside that you can just get your data from wherever and then call `addData()` on the cluster layer and it will recluster for you using the new data.

Note: In the plunker, if you pan the map the flares will go all wonky when hovering over a cluster - something to do with how it's hosted in plunkr, don't worry about it though.

**Comment by DOOMitru** [comment]
Great! I was able to make it work with your help.  Thanks very much for the help and the quick response!

**Comment by nickcam** [comment]
No problems, glad you got it going!

**Comment by DOOMitru** [comment]
Just wanted to show you the result: ![result](http://i.imgur.com/hvO1VV8.png)

We've plotted over 600k points and it took less than a minute to render it all clustered.  We did this using MarkerClusterer v3 for Google Maps and it took almost 40 minutes.  

Great job! And thanks again!

**Comment by nickcam** [comment]
Wow, that's a lot of points - I'm glad...and slightly surprised :)...it worked ok for that many!
