### ISSUE TITLE
only support webMercator basemap?

### ISSUE THREAD

**Issue by dyh333** [nickcam/FlareClusterLayer#16]
hi, @nickcam . i like this flareclusterlayer very much. thanks your share. but i found that the source code seems convert all graphic to webMercator project? does it means that the layer only can add to webMercator basemap?

**Comment by nickcam** [comment]
Hi @dyh333,
Yeah thats right...it does this as I found that wrap around in a MapView didn't work unless all points were in web mercator. I haven't tested using a basemap that isn't in web mercator to be honest, but it would not surprise me that it wouldn't work.  

This may change in v4.2 and on, so can hopefully remove the explicit conversion. If you don't mind wrap around being an issue, you could just remove the conversions and you should be good. Alternatively you could add a property to the class to control whether or not all points are converted so it can be configured.

Thanks,
Nick

**Comment by dyh333** [comment]
@nickcam, thanks your reply. i will try as your advice.
