### ISSUE TITLE
"import * as X" versus "import X" with esri Modules

### ISSUE THREAD

**Issue by netik25** [nickcam/FlareClusterLayer#18]
Note: This is NOT an issue with your project, but more of a question because of my lack of competence and you seem very competent.

Hi Nickcam, 
First of all: Amazing project! I would love to use it in my project. I'm having one question though.

Your way of importing esri modules, like for example:

`import * as Graphic from "esri/Graphic";`

does not work when I use your .ts file in my project, because it cannot find the constructor of the esri Modules. I usually need to import them like

`import  Graphic from "esri/Graphic";`

Any idea what that could be? 

I am using the exact same tsconfig.json settings, but I'm transpilling with tsc instead. Also I have included the typings.

**Comment by netik25** [comment]
ahh, I'm very sorry, I just read on your markdown file that this is because of Angular2? I am using Angular2, so that must be it. Very sorry

**Comment by nickcam** [comment]
Hi @netik25,
Yeah there's different patterns for angular2. Just for reference here's some other repos that may help you get started quickly
[https://github.com/nickcam/Ang2-Esri-NetCore/tree/master/Ang2-Esri-NetCore](https://github.com/nickcam/Ang2-Esri-NetCore/tree/master/Ang2-Esri-NetCore)
[https://github.com/tomwayson/angular2-esri-example](https://github.com/tomwayson/angular2-esri-example)
[https://github.com/tomwayson/esri-angular-cli-example](https://github.com/tomwayson/esri-angular-cli-example)
Thanks,
Nick
