### ISSUE TITLE
JSAPI V 4.2 compatibility

### ISSUE THREAD

**Issue by netik25** [nickcam/FlareClusterLayer#19]
Hi Nick
Looks like version 4.2 of the JSAPI has been released a few days ago - unfortunately the documentation is not up to date yet, but it seems to be breaking FCL. 

It cannot find the 2D VectorGroup - hopefully it was just renamed/moved and not removed from the JSAPI.

PS. let me know if there is some way to donate something to your great work! I could really use this feature in my application, but we also need the new features of 4.2 :)

Best regards
Netik

**Comment by nickcam** [comment]
Hi @netik25,

Yeah I totally expected it to break for v4.2. I've started building a new version of FCL for v4.x that will hopefully be a bit more future proof and only use the public classes from the api. 

Once ESRI updates the API documentation I'll look at updating it to work with v4.2 as I also need to make use of some of the new features. Can't give a time frame though sorry.

Thanks,.
Nick

**Comment by nickcam** [comment]
Hi @netik25,
Just committed a new version into the master branch that supports v4.2. Let me know how you go with it.
Thanks,
Nick
