### ISSUE TITLE
JSAPI 4.1 TypeScript

### ISSUE THREAD

**Issue by payneBrandon** [nickcam/FlareClusterLayer#21]
I'm running into an issue with the 4.1 typescript file.  I had been using the 4.2 which was working beautifully, but ran into a separate bug in the ESRI code with removing a FeatureLayer and need to fall back to the 4.1 API.  I'm running Angular 2 and load with systemjs.  When the 4.1 typescript file is loaded, the constructor is throwing an error on the following line: 
`this.on("layerview-create", (evt) => this.layerViewCreated(evt));`

The exception is "EXCEPTION: TypeError: _this.on is not a function".  Its almost as though the transpiled JS isn't understanding what 'this' should be.  Any ideas on this?

**Comment by nickcam** [comment]
Hey man, yeah that's odd. I was using that same version in an angular 2 app no problems. I've just tried it out by putting the 4.1 version into this repo - [https://github.com/nickcam/angular2-esri-netcore](https://github.com/nickcam/angular2-esri-netcore) and I got the same error.

For some reason it appears the Evented mixin that is part of a GraphicsLayer and contains the 'on' function isn't available in the constructor.  It is in other functions within the layer though.

Here's some hacks to get around the error. Move this line out of the constructor: 
` this.on("layerview-create", (evt) => this.layerViewCreated(evt));`

Create a new function: 
```
init() {
     this.on("layerview-create", (evt) => this.layerViewCreated(evt));
 }
```

Call the `init()` function directly after you instantiate the layer. ie:
```
 let fcl = new FlareClusterLayer({});
 fcl.init();
```

This is not pretty I know!
If you come up with a better solution please let me know :)! 
To be honest I'm not going to spend time chasing this down as the non angular 2 version for 4.1 is still working, plus it's not the latest version anyway...the arcgis api is in a constant flux so not sure how relevant 4.1 will be in a 1 - 2 months. 

Let me know how you go.

**Comment by payneBrandon** [comment]
Hey, thanks for looking into it a bit for me!  I'm not sure if its just my machine but I keep running into issues when referencing the FlareClusterLayer properties using 'this'.  I was able to get around the errors by pulling everything from the constructor (except the super()) and adding it to a new init() function.  This seems to get rid of the errors thrown, however is now not clustering properly.  I see the number that is usually displayed in the cluster but not the cluster itself or the animations that usually accompany hovering over a cluster.  I'll keep digging and let you know if I come up with a solution to this.  Maybe I'll get lucky and ESRI will fix the issue with the FeatureLayer in 4.2 that is holding me back from that version...

**Comment by nickcam** [comment]
No probs. What errors are you getting in the console? The only line that should have to move from the ctor is the "on" one as all of the other lines just set properties specific to flareClusterLayer, so it's weird that they would throw errors.

Actually, try one other thing - in the FlareClusterVectorGroup class change this block in the `draw(a)` method:

```
//only applies to 2d and only if there's vectors to draw
        if (this.layer.activeView.type !== "2d" || this.vectors.length === 0) {
            return;
        }
```

To this
```
//only applies to 2d and only if there's vectors to draw
        if (!this.layer.activeView || this.layer.activeView.type !== "2d" || this.vectors.length === 0) {
            return;
        }
```

**Comment by payneBrandon** [comment]
If I leave everything in the constructor, its throwing an error on the this.drawData():
 "EXCEPTION: TypeError: _this.drawData is not a function"
If I move just the drawData function call out to the init, I run into issues down the line as well. Its acting as though the variables set in the constructor aren't recognized later in the other functions.  For instance the textSymbol is set in the constructor, however later 'this.textSymbol.clone' throws an error because this.textSymbol is undefined.

**Comment by nickcam** [comment]
Ah right. Yeah that's really strange. Perhaps it's something to do with where it's being constructed, as in too early, before the arcgis scripts have fully loaded?? I don't think that's right though as I was getting the same error and I'm pretty sure they were all loaded, that's all I can think of right now though. Sorry mate, don't have the capacity to look into it more right now. Let me know how you go.

**Comment by payneBrandon** [comment]
Hey man, thanks for all the help with this.  Getting the 4.1 version up and running was proving to be too much work, so I am back with the 4.2 version (working beautifully btw) and have just added a work-around for the ESRI issue I was running into.  I'll go ahead and close it out with that, again thanks for the help and a sweet cluster layer!

**Comment by nickcam** [comment]
No worries man, glad you got it going...probably best to stick with the latest version as well :)!
