### ISSUE TITLE
Tooltip for individual points

### ISSUE THREAD

**Issue by apaleja** [nickcam/FlareClusterLayer#24]
Is it possible to activate/add tooltip similar to cluster flare tooltip, for individual points which are not in cluster ?

**Comment by nickcam** [comment]
Hi @apaleja, yeah it is totally possible, but I don't think it's something that should live in this project. As the individual points are just normal graphics I think a separate tooltip component would be better that could be reused across any layer. 

I've done this in a separate app (not on github though) and it works pretty well. Here's some typescript pseudo code that may help you out.

You could also add it into your own version of FlareClusterLayer if you really wanted.

```javascript

setup() {
 // TODO: create mapView or sceneView and assign it to the view property.
 this.view.on("pointer-move", (evt) => this._viewPointerMove(evt));
}

private _viewPointerMove(evt) {
   // a function to return the mouse position based on the event parameters. 
   let mousePos = this._getMousePos(evt); 
   
  // use views hitTest function
   this.view.hitTest(mousePos).then((response) => {
     let graphics = response.results;
     if (graphics.length === 0) {
       // TODO: no graphics currently hovered over, hide any open tooltips and exit
       this.tooltip.hide();
       return;
     }

    // TODO: show a tooltip for the graphics at the mouse pos. ie, create a html element containing whatever content you want based on a graphics attributes.
      this.tooltip.show(graphics, mousePos);

  });
}

 private _getMousePos(e) {
      let container = <HTMLDivElement>this.view.container;
      let rect = container.getBoundingClientRect();
      return {
          x: e.x - rect.left,
          y: e.y - rect.top
      };
 }

```

**Comment by apaleja** [comment]
@nickcam Thank you very much for quick reply. This surely will help me.
