### ISSUE TITLE
init.js:327 [esri.core.Accessor] Accessor#set Assigning an instance of 'FlareClusterLayer' which is not a subclass of 'esri.Graphic'

### ISSUE THREAD

**Issue by yzf1116** [nickcam/FlareClusterLayer#25]
What is the reason for this?

**Comment by nickcam** [comment]
Hi @YangZhenFang, sorry mate, not really enough detail in your issue to comment on fully. 
Is the error occurring in your own version of the layer? 
From the sounds of it you're trying to assign an instance of FlareClusterLayer to a graphic object, which obviously won't work as it's a layer not a graphic.
Are you using v3.x or v4.x?
Do you have an example page where this occurring?

**Comment by yzf1116** [comment]
Thank you reply to me,@nickcam， i was the first to use arcgis, the version is 4.5, there are many do not understand.now is that
![8eecf378-891f-44d8-9926-359e6f93387b](https://user-images.githubusercontent.com/13129167/32083812-14eede8a-ba8b-11e7-9a29-f3fc8bf94db2.png)

this is data


![image](https://user-images.githubusercontent.com/13129167/32084246-971dd490-ba8d-11e7-89cc-a1630aa9f6c8.png)

**Comment by nickcam** [comment]
Hi, sorry still can't really see what the issue is. Do you have a live example somewhere (jsfiddle, plunker) where it can be demonstrated?

As your coordinate fields are named Lat and Lng you'll need to set these properties in the constructor options when instantiating a FlareClusterLayer.

```javascript
var fcl = new FlareClusterLayer({
   xPropertyName: "Lng",
   yPropertyName: "Lat"
});
```

**Comment by yzf1116** [comment]
sorry to bother you
http://jsfiddle.net/Hide_Ekko/ma1r1a8g/
in 672-773

**Comment by yzf1116** [comment]
now no error,but not show the mapView

**Comment by nickcam** [comment]
Hi mate, I can't see anything wrong in the jsfiddle...but it doesn't run. Do you have a sample that runs that is displaying the error?
