### ISSUE TITLE
[Feature Request] Strengthen with vue support

### ISSUE THREAD

**Issue by feverdestiny** [nickcam/FlareClusterLayer#27]
## FlareClusterLayer version
4.X
## Arcgis for js  version
4.5
## Vue version
2.5.2
## problem
Hi Nick，Thank you for providing this project，i'm  a  vue user ,i having a problem using this open source project，i use _FlareClusterLayer_v4.js_ import to my project ,but it not  work,finally，i find
this is the Vue and TypeScript integration has always been flawed. [https://vuejs.org/v2/guide/typescript.html#Recommended-Configuration](https://vuejs.org/v2/guide/typescript.html#Recommended-Configuration),so i clone to locally,i'm modify _tsconfig.json_ `"strict": true,` and  run `typescript-compile` in VS Code ，but it compile failed

**Comment by nickcam** [comment]
Hi @feverdestiny, sorry I've never worked with Vue so don't know how to help with integration. 
If you haven't already, a good place to start would be to get a Vue typescript application that successfully loads ArcGIS api v4.5 up and running. 

After that copying in the flareClusterLayer typescript file so that it compiles with the rest of your app shouldn't be too difficult. It may require some tweaking depending on how you're loading modules though.

**Comment by feverdestiny** [comment]
Thank you reply @nickcam ,ArcGis api 4.5 runing my vue project,now i find if vue project use you `FlareClusterLayer_v4.js`,
js text `this` will can not automatically deduce `this` type，
The solution I'm looking for now is to add "strict: true" to tsconfig.json and then refactor the typescript files into js files，but when i run `typescript-compile` in VS Code,you code failed. I know very little about typescript，so i hope compile to give me a new js file
Thank  to

**Comment by feverdestiny** [comment]
![image](https://raw.githubusercontent.com/feverdestiny/screenshot/master/tpescript.png)

**Comment by nickcam** [comment]
Hi @feverdestiny, looks like strict mode might be causing an issue. 
Also the module type is set to amd, this is for compatibility with arcgis jsapi....I'm not sure if this will suit your project or not. 

How are you loading the arcgis api and then using it within vue? At the same point you do this, you may be able to include the already compiled flareClusterLayer_v4.js file to save you having to compile the typescript yourself.
