### ISSUE TITLE
The cluster graphic did not show corretly

### ISSUE THREAD

**Issue by narimdcg** [nickcam/FlareClusterLayer#28]
Hi,
Thank you for your code, but the graphics of the clusterlayer seems to be trimed by a boundbox sometimes.

Looking forward to your help,Thands a lot!

**Comment by nickcam** [comment]
Sorry mate, not sure what you mean. Need more info...a demo page or plunk or fiddle displaying the problem would be best.

**Comment by narimdcg** [comment]
![clusterlayer](https://user-images.githubusercontent.com/31976085/33970052-d95b2c60-e0ab-11e7-9f58-73dccd6522d0.png)

This  appeared  on my computer yesterday afternoon.Both with my local code and yours on the site.But  worked correctly this morning(UTC/GMT+08:00).It seems like this happened when the tiles didn`t loaded completely due to the awful Internet situation.

Thanks for your attention. Looking forward to more excellent examples both in(ArcGIS JS API 3.x & 4.x).

**Comment by nickcam** [comment]
Ah ok. Yeah that does look strange.  Glad it's working for you now!
