### ISSUE TITLE
Map object initialization

### ISSUE THREAD

**Issue by PavelVeselsky** [nickcam/FlareClusterLayer#3]
How is the `_setMap` method called? In the example, it's called automatically, but I had to set the map explicitely. Why? Does it look for `map` and `surface` objects at some specific locations?

**Comment by nickcam** [comment]
Hi @PavelVeselsky,

_setMap is an internal GraphicsLayer method that I've overriden to add some events. It should get called when you add the layer to the map. ie:

`map.addLayer(clusterLayer);`

Obviously it will only be called if your class is still inheriting from GraphicsLayer though.

`
 return declare([GraphicsLayer], {
        constructor: function (options) { .....
`

Thanks,
Nick

**Comment by PavelVeselsky** [comment]
To reference the class stored in custom location, I named it:

```
define("cluster/FlareClusterLayer", [
    "dojo/_base/declare",
    ...

return declare("cluster.FlareClusterLayer", [GraphicsLayer], {
    ...
```

Naming works in respect to the referencing, but might have broken the inheritance from GraphicsLayer? AFAIK it should work, but I'm still far from black belt level in Dojo, so I might have misunderstood something. I will try to reference the project some other way to test it.

**Comment by PavelVeselsky** [comment]
Indeed, naming the classes is not the right way, but [doing it the right way is not that easy to understand](http://stackoverflow.com/q/35867005/1801588). I'm looking forward to the moment I'll understand it enough to see if this was the source of my troubles or not.

Anyway, thank you!

**Comment by PavelVeselsky** [comment]
[I don't need the module name any more](http://stackoverflow.com/a/35895455/1801588), so I tested it and `_setMap` is still not called. It IS inherited from the GraphicsLayer and GraphicLayer is on its place in require - function pair in the define statement, so I don't know. My only idea is that it might have a problem to find the surface variable - while trying to call it explicitly, I didn't find and had to make it anew. But GraphicsLayer should handle it... I'll try to understand how GraphicsLayer works under the hood to find out whether the source of the problem is there or not, like a clash with some other part of our project.

**Comment by nickcam** [comment]
Yeah dojo is far from my favorite library as well, I get thoroughly confused by it at times as well :). 
If you're still having issues, you can send me your class if you like and I can have a look when I get a chance.

**Comment by PavelVeselsky** [comment]
My code needs some polishing and commenting before I can responsibly publish it, off course with the readme changed to "use nickcam's version, mine is a testing/debugging build, not really working". I have already forked FlareClusterLayer and I'll update it with my code and let you know, but it will take me days or weeks.

**Comment by nickcam** [comment]
No worries. I'll close this issue. Just let me know if you want any help.

**Comment by PavelVeselsky** [comment]
I test it with your example front-end (index.html, data.json and DataManager.js) and I don't need to initialize the map with them. I'll try to find out which difference between your static and my Orchard-generated page causes the issue. Anyway, this issue should stay closed, the problem is not in FlareClusterLayer.
