### ISSUE TITLE
Flares do not activate when a completely new cluster layer is initialized

### ISSUE THREAD

**Issue by mdominado** [nickcam/FlareClusterLayer#32]
Apologies for another issue at hand. But I ran into this issue when I started testing out my code that destroys the previous cluster layer and completely instantiates a new cluster layer on the map.

To be clear, I'm storing the cluster layer globally and adding it to the map (specifically a group layer) when I first initialize it, and then when I decide to go create a new one, I make sure to remove the cluster layer from the group layer, and set the global variable to be null, so there's no references whatsoever to the cluster layer anymore.

Now getting to the issue at hand, when I create a new one, with the same process as mentioned above (store globally, adding to group layer), and I try to hover over a cluster to see the flares associated with the cluster, it does not show the flares for any of the clusters anymore.

I did do some digging today and noticed when it tried to activate the cluster, it could the not find the cluster id in the associated _this_.clusters object. 

                        var cluster = _this._clusters[g.attributes.clusterId];

I believe that is the issue, but I do not understand why it would it would not be there anymore.

Anyways, as usual, any help at all is appreciated!

**Comment by nickcam** [comment]
Ok, that sounds odd.  I haven't tried adding it to a group layer or adding and removing references to it before - feel like perhaps the LayerViews might get screwed up. Are you able to create a plunkr (or some other sandpit site) that replicates it?

**Comment by mdominado** [comment]
I tried to create the sample on some of the sandpit sites, plunkr, jsbin, etc, and I couldn't get it on there for some reason, maybe I'm doing some wrong. However, I just reused your v4 sample and modified the code in the index html file to recreate the cluster layer and have it added to a group layer instead. Here's the modified file. 

[index_v4.zip](https://github.com/nickcam/FlareClusterLayer/files/2184948/index_v4.zip)

I also ran into the same issue doing so in the sample. If you click the recreate text button in the menu, it should destroy and create a new cluster layer, and add it to a group layer.

**Comment by mdominado** [comment]
OK, bit of an update, my initial thought that maybe adding the cluster layer to a group layer was the cause, since you mentioned that you never tried adding it to a group layer. Unfortunately, that doesn't seem to be the case. I changed it to be directly added to the map's layers itself, and same issue is produced.

**Comment by mdominado** [comment]
Another update upon debugging the issue via the browser's developers' tools. So whenever I recreate a cluster and hover a cluster again, I get different cluster objects in the _this._clusters object.

For example:

When I move the map the stored cluster objects ids are 159, and 161 initially. It clears the map to draw again, and the cluster objects become 172, and 174. However, once the clusters are done drawing on the map, and I go to hover over the clusters again, the flare cluster layer thinks it has 159, and 161, when it really has the newer values - 172, and 174. Additionally, I can verify that 172, and 174 are on the map, by hovering over the clusters, and looking through the global flare cluster layer object that I have stored.

So, now my thoughts are that there's something not being referenced right somewhere.

**Comment by mdominado** [comment]
OK I managed to get a plunkr sample set up, it looked like the issue was the data.json being too big of a file. Anyways, if you could check it out as soon as you get the chance that would be great!

Here's the link:
https://next.plnkr.co/plunk/DmddmXz2Vb06i5rj

**Comment by nickcam** [comment]
Ok cool. Thanks the plunkr is very helpful.

So there's definitely a bug when you instantiate a layer for the second time. As you already found something to do with reading the uid's from the graphics created when adding a cluster. I didn't dig into the cluster layer code any more to try and fix it though as I still plan on rewriting that whole part soonish.

It should be easy enough to get around though. Have updated the plunk here - [https://plnkr.co/edit/2ajpktcDboVtoflI?p=info](https://plnkr.co/edit/2ajpktcDboVtoflI?p=info)

See the updated event handler for the recreate button click,

Instead of setting to null and re-instantiating, just remove the layer from the map...then make any changes you want to make to it by setting the appropriate properties on the layer object. Then re-add it to the map. Could also just set visible to false, and then true when ready again if you don't care it it stays in the layers collection.

**Comment by mdominado** [comment]
Nice! That definitely is a workaround. I forgot to update you and let you know that I ended up changing my code to just reuse the same flare cluster layer instance so there is no need for a new flare cluster to be created every time. 

I'll keep your workaround in mind for when there will be a time that I will need to create a new instance, instead of reusing the same one. 

Thanks for at least taking the time to taking a look at the issue though! Much appreciated.

**Comment by nickcam** [comment]
Ok cool, glad you got it going! The workaround I posted is the same as yours, just don't create a new instance and reuse the existing one.
