### ISSUE TITLE
Use with other projection (27700)

### ISSUE THREAD

**Issue by mtrsklnkvMM** [nickcam/FlareClusterLayer#34]
Hi,

I am trying to make it work in British National Grid (27700).
It came up with an error message when trying to get the "webExtent" in the code, which I "solved" by using the geometry service project tool instead. All the clusters seem to generate ok in code(although only when I pass decimal degrees coordinates), but they don't show on the map.

Any idea?

Thanks,
Matt

**Comment by nickcam** [comment]
Hi @mtrsklnkvMM, I only ever tested using 4326 and web mercator. I can't think of any reason off the top of my head why using the geometry engine to convert between any spatial reference and web mercator wouldn't work though. Are you able to create a demo page using plunkr or something that demonstrates the issue?

**Comment by mtrsklnkvMM** [comment]
Hi,
I was able to make it work. 
It was linked to an esri issue/bug, that was shifting all my points by quite a lot. (https://community.esri.com/thread/91409)
It's working great now, thanks for the answer. Really useful widget.
