### ISSUE TITLE
Chrome 70 ruined the flare...

### ISSUE THREAD

**Issue by orengal** [nickcam/FlareClusterLayer#35]
Since last update of Chrome the flare is cut inside a small rectangle
Have no clue

**Comment by nickcam** [comment]
Hi @orengal - yep I'm seeing it as well, really is quite busted. 
I thought it would be pretty simple to fix at first with an overflow: visible being needed somewhere, but they seem to be everywhere they should be.

Looks like the svg group (<g>) elements aren't honouring overflow. Haven't been able to fix it yet - if you come up with anything let me know.

**Comment by orengal** [comment]
Hi @nickcam,
Will try. 
In Chrome 72 it works again so I guess it's a bug Google put, saw and solved.

**Comment by nickcam** [comment]
Hi @orengal - ok cool. Don't happen to know when 72 will be released as the prod build do you?

**Comment by orengal** [comment]
Hi @nickcam,
No, I have 70 and Canary 72. If it's fixed in 71 it's less than a month. Google update is every month.
I have asked Google if they can make a hotfix to 70 thou.

**Comment by nickcam** [comment]
Thanks man. I just tried 71 and it's no good either. I'll keep looking for a workaround when time permits, but hopefully a hotfix will come in before 72 is released.

**Comment by nickcam** [comment]
Looks like this was actually fixed in 71.
