### ISSUE TITLE
ArcGIS Javascript API 4.10 - 4.11

### ISSUE THREAD

**Issue by roy0633** [nickcam/FlareClusterLayer#37]
Hi~
When I use ArcGIS Javascript API 4.10
I received an error message about "engine/graphics/GFXObject"

**Comment by nickcam** [comment]
Hi @roy0633,

Since v4.10 all drawing is done using webgl, so no more svg - which is a good thing. 
Now it can draw 1000's of points with no performance drawback, so clustering may not be necessary.

This layer is using svg to create a clone of the svg graphic to use as a cluster container, that will obviously no longer work. It can be fixed but would require a pretty big rewrite, not sure when I'll have capacity to do it though sorry. 

Anyone is welcome to try out updating it if they have the time.

**Comment by roy0633** [comment]
Thank you very much!
My English is not good, maybe I can't express my gratitude correctly.
I am developing a website related to the price of real estate. When the price of each area is displayed on the map, the total amount of information is often tens of thousands. The FlareClusterLayer has helped me a lot.
![image](https://user-images.githubusercontent.com/46474785/51009302-a3d7a680-158a-11e9-8182-4c67f652df7c.png)
(New Taipei City)

**Comment by nickcam** [comment]
Ok cool, screenshot looks good! If you're relying on the layer then for the moment you'll have to stick with arcgis v4.9. As you've found out it definitely won't work in 4.10. I'll have to find time to update it, but don't know when that will be.

**Comment by mattfr** [comment]
Hi,
We were very happy using the cluster layer too, hopefully you will find some time eventually to fix it. I'd give it a go, if I only knew where to start!

**Comment by mtrsklnkvMM** [comment]
Hi,
We were happy using the cluster for our project too.
Hopefully you will find the time to fix it eventually, I'd give it a go if I knew where to start!

**Comment by roy0633** [comment]
@mtrsklnkvMM 
I substitute
v4.9 "esri/views/2d/engine/graphics/GFXObject", "esri/views/2d/engine/graphics/Projector", 
--> v4.10  "dojox/gfx3d/object", "@dojo/framework/widget-core/mixins/Projector",
And close _activateCluster and _deactivateCluster for work

**Comment by stalniy** [comment]
@nickcam maybe you can give some hints or direction where to look (start from), so we can help you to upgrade

**Comment by nickcam** [comment]
Hi @stalniy - that is a good idea!

What happens now at a high level:
When a cluster is moused over or tapped on, `_activateCluster()` is called. This performs the following steps.
 - an svg surface element is moved to the position of the mouse over graphic.
 - Clones of the moused over graphic and text object are created and added to the svg surface as new svg elements.
- Flares are added to the surface element as well, again it uses clones of a graphics object to do this.

The busted part in v4.10 is in the creating clones of graphic objects. The esri modules used to do this no longer exist (or they've moved somewhere else).
`"esri/views/2d/engine/graphics/GFXObject"`
`"esri/views/2d/engine/graphics/Projector"`

So this function will no longer work and needs to be rewritten or replaced/removed altogether.
`_createClonedElementFromGraphic(graphic: Graphic, surface: any)`

Thinking about it quickly a possible solution could be -
- Don't create clones of the moused over graphics and just leave them as is. This means you can't add css animations to the moused over graphics, might not be an issue really.
- Don't clone the flare graphics either and just create them as svg elements directly. This would change how the flares are styled...as in I don't think a class breaks renderer would work for them. Again may not be an issue if you're just happy to use circles all the time, and/or possibly give some basic options like circle, rectangle, diamond with size, color and other options etc...
- Text graphics are used to generate text, now that labelling is supported in Map Views, could get rid of the text graphics and just use labels.

Overall might lose some styling functionality to begin with, but may not be a full rewrite as I was first thinking.

**Comment by davidpelayo** [comment]
Any update on this?

**Comment by nickcam** [comment]
No progress yet, did just start looking at it today though. 
I don't use this library in my work projects anymore, so I need to find spare time to update it, which is extremely sparse, so can't commit to when it will be done sorry.

**Comment by nickcam** [comment]
Thanks for the PR @davidpelayo.
There's a branch that just has clustering with no flares for v4.11. 
It's called v4.11-noflares. If you just want clustering and don't mind not having flares, then just use this branch.

**Comment by roy0633** [comment]
My website for 4.11 with click event
[OCom_2019_04_04_10_59_50_632.zip](https://github.com/nickcam/FlareClusterLayer/files/3041544/OCom_2019_04_04_10_59_50_632.zip)

                v.fclPointerMove = v.on("pointer-move", function (evt) { return _this._viewPointerMove(evt); });
                v.fclPointerDown = v.on("pointer-down", function (evt) { return _this._viewPointerDown(evt); }); //ROY0633 


FlareClusterLayer.prototype._viewPointerMove = function (evt) {
            //Before...
        };
        FlareClusterLayer.prototype.**_viewPointerDown** = function (evt) {
            var _this = this;
            var mousePos = this._getMousePos(evt);
            if (this._activeCluster && this._activeCluster.clusterGroup) {
                var bbox = this._activeCluster.clusterGroup.rawNode.getBoundingClientRect();
                if (bbox) {
                    if (mousePos.x >= bbox.left && mousePos.x <= bbox.right && mousePos.y >= bbox.top && mousePos.y <= bbox.bottom)
                        return;
                }
            }
            if (!this._activeView.ready)
                return;
            var hitTest = this._activeView.hitTest(mousePos);
            if (!hitTest)
                return;
            hitTest.then(function (response) {
                var graphics = response.results;
                if (graphics.length === 0) {
                    _this._deactivateCluster();
                    return;
                }

**Comment by roy0633** [comment]
My website for 4.11 with SceneView
[Ocam_2019_04_04_11_14_54_389_Trim.zip](https://github.com/nickcam/FlareClusterLayer/files/3041610/Ocam_2019_04_04_11_14_54_389_Trim.zip)

**Comment by roy0633** [comment]
> My website for 4.11 with click event
> [OCom_2019_04_04_10_59_50_632.zip](https://github.com/nickcam/FlareClusterLayer/files/3041544/OCom_2019_04_04_10_59_50_632.zip)
> 
> ```
>             v.fclPointerMove = v.on("pointer-move", function (evt) { return _this._viewPointerMove(evt); });
>             v.fclPointerDown = v.on("pointer-down", function (evt) { return _this._viewPointerDown(evt); }); //ROY0633 
> ```
> FlareClusterLayer.prototype._viewPointerMove = function (evt) {
> //Before...
> };
> FlareClusterLayer.prototype.**_viewPointerDown** = function (evt) {
> var _this = this;
> var mousePos = this._getMousePos(evt);
> if (this._activeCluster && this._activeCluster.clusterGroup) {
> var bbox = this._activeCluster.clusterGroup.rawNode.getBoundingClientRect();
> if (bbox) {
> if (mousePos.x >= bbox.left && mousePos.x <= bbox.right && mousePos.y >= bbox.top && mousePos.y <= bbox.bottom)
> return;
> }
> }
> if (!this._activeView.ready)
> return;
> var hitTest = this._activeView.hitTest(mousePos);
> if (!hitTest)
> return;
> hitTest.then(function (response) {
> var graphics = response.results;
> if (graphics.length === 0) {
> _this._deactivateCluster();
> return;
> }

**Comment by pyalam** [comment]
@roy0633 :thank you but im looking like this .when you click on a cluster it should zoom into the points of extents 
like how they are showing in the below url
http://esri.github.io/cluster-layer-js/styled.html

please help me if you know

**Comment by nickcam** [comment]
Update on this. Just committed a fully working version for v4.11, flares included. It's now the master branch.
 
v4.12 needs some more work as it isn't compatible, but esri haven't published the @types for 4.12 yet so I'm going to wait until they're out until getting it running. Will track v4.12 support in a different issue.

**Comment by stalniy** [comment]
Awesome news @nickcam ! Thanks a lot for the support!
