### ISSUE TITLE
flareCluster displaced when map is not full body, and after pan

### ISSUE THREAD

**Issue by tdimanov** [nickcam/FlareClusterLayer#4]
Hi nickcam,

thanks for your cluster extension. I tried to used it in map instance which is not 100% of the body span. I noticed flareCluster has been displaced from the cluster group center on mouseover. I'm attaching screenshot of that.
Thanks in advance for your input on that issue.
<img width="944" alt="screen shot 2016-04-14 at 10 07 51 am" src="https://cloud.githubusercontent.com/assets/10978705/14530865/ddc43340-0228-11e6-89b2-6e6c4d54af35.png">

**Comment by tdimanov** [comment]
I actually resolved the problem by modifying FlareClusterLayer.js (lines 909, 910) this way:
            pt.x = fo.center.x - mapDivLeft;
            pt.y = fo.center.y - mapDivTop;

where mapDivLeft and mapDivTop were previously defined as:
            var mapDivLeft = $("#map").offset().left;
            var mapDivTop = $("#map").offset().top;

I'm sure there is more elegant solution. Thanks for your work!

**Comment by nickcam** [comment]
Good stuff, glad to hear you sorted it and thanks for the fix. I'll close this issue and incorporate it into a new version at some stage.
Thanks,
Nick
