### ISSUE TITLE
Using in Angular app

### ISSUE THREAD

**Issue by nickcam** [nickcam/FlareClusterLayer#41]
when i do this https://github.com/Esri/esri-loader#configuring-dojo
i dont need to npm install dojo typings right?
somehow its giving me 
 ` http://localhost:4200/fcl/FlareClusterLayer_v3.js net::ERR_ABORTED 404 (Not Found)`

thank you

_Originally posted by @dealsmyself in https://github.com/nickcam/FlareClusterLayer/issues/22#issuecomment-463896664_

**Comment by nickcam** [comment]
Hi @dealsmyself,

If you're using v4.x of the arcgis api you'll need to include FlareClusterLayer_v4.js, not the v3.js file.
You'll need to copy the js file FlareClusterLayer_v4.js somewhere you're app can reference it, like any other script file, possibly to the `assets` folder.

No you don't need to include the typings, as the js file is already compiled as a complete amd module.
If you can't get it working might be worth posting an issue on the esri-loader repo asking for guidance.

**Comment by dealsmyself** [comment]
Hi @nickcam 
the error i  get when i try to compile the js file by adding to scripts:[] is
`ReferenceError: define is not defined` in FlareClusterLayer_v4.js

**Comment by nickcam** [comment]
You shouldn't need to add anything to scripts[]?
Follow the instructions here - [https://github.com/Esri/esri-loader#configuring-dojo](https://github.com/Esri/esri-loader#configuring-dojo) and you'll just add the js file location and name to the packages array in dojoConfig.

**Comment by dealsmyself** [comment]
Thank you very much @nickcam , my issue is resolved. thanks for all the help.i will try to create a stackblitz for others with the issue.
