### ISSUE TITLE
flares not showing up in angular app

### ISSUE THREAD

**Issue by pyalam** [nickcam/FlareClusterLayer#44]
Hi nick,

I have created your sample inside my angular app just by copying your code.here the flares are not showing on tool tip of the cluster group.please see attached folder for the code.if possible can you please add your example sample inside angular component to see whether they are actually working or not.
[fleet-map (2).zip](https://github.com/nickcam/FlareClusterLayer/files/2878314/fleet-map.2.zip)

![image](https://user-images.githubusercontent.com/8193674/52990619-b5ed0600-33ce-11e9-9ca0-7f37befa0794.png)

**Comment by nickcam** [comment]
Hi @pyalam, I don't have time to crack open your whole project, compile it, trouble shoot it and return it. If you're able to reproduce the same problem in an online editor of some type (stackblitz, jsfiddle, codepen, plunkr), I'm happy to take a look at that.

**Comment by pyalam** [comment]
No problem nick.Can you please let me know why when i mouse point on other regions some other flares are showing up on cluster.Do you know why my mouse over event is not catching the cluster position.can u see the attached screen shot.here i was moving my mouse some where and some where else flares are showing up.where i need to trouble shoot this.
![20190218_232855](https://user-images.githubusercontent.com/8193674/52992258-8ee60280-33d5-11e9-8ea9-c5bdc9fa13e7.jpg)
