### ISSUE TITLE
checking the mouse point inside the  actual circle of the cluster group and it's flares instead of using the rectanglar bounding box

### ISSUE THREAD

**Issue by pyalam** [nickcam/FlareClusterLayer#45]
HI Nick,

Im working on finding the mouse pointer inside the cluster group circle and show the flares because the rectangle box is not working for me.Do you know how to find the mouse pointer inside the cluster group and see if the pointer is inside or not.

 FlareClusterLayer.prototype._viewPointerMove = function (evt) {
			//alert("pointermove");
            var _this = this;
            var mousePos = this._getMousePos(evt);
			
            // if there's an active cluster and the current screen pos is within the bounds of that cluster's group container, don't do anything more. 
            // TODO: would probably be better to check if the point is in the actual circle of the cluster group and it's flares instead of using the rectanglar bounding box.
			
			
            if (this._activeCluster && this._activeCluster.clusterGroup) {
				//return;
				//console.log("active cluster pointer move");
				console.log(mousePos);
				console.log(this._activeCluster);
                var bbox = this._activeCluster.clusterGroup.rawNode.getBoundingClientRect();
				//console.log(bbox);
				return;
				//console.log(mousePos.x);
				//console.log(bbox.left);
				//console.log(bbox.right);
				//console.log(mousePos.y);
				//console.log(bbox.top);
				//console.log(bbox.bottom);
               // if (bbox) {
					//mousePos.x = bbox.left + bbox.left;
					//bbox.left = (bbox.left - mousePos.x);
					//bbox.right = (bbox.right);
					//bbox.top = (bbox.top - mousePos.y);
					//bbox.bottom= (bbox.bottom - 200);
					//mousePos.y = bbox.top+bbox.top;
					
                    //if (mousePos.x >= bbox.left && mousePos.x <= bbox.right && mousePos.y >= bbox.top && mousePos.y <= bbox.bottom)
                      //  return;
                //}
            }else{
				this._destroyTooltip();
			}
            if (!this._activeView.ready)
                return;
            var hitTest = this._activeView.hitTest(mousePos);
			//console.log(hitTest);
            if (!hitTest)
                return;
            hitTest.then(function (response) {
                var graphics = response.results;
                if (graphics.length === 0) {
					//console.log("no graphics");
                    _this._deactivateCluster();
                    return;
                }
                for (var i = 0, len = graphics.length; i < len; i++) {
					
                    var g = graphics[i].graphic;
					//console.log(g);
                    if (g && (g.attributes.clusterId != null && !g.attributes.isClusterArea)) {
                        var cluster = _this._clusters[g.attributes.clusterId];
                        _this._activateCluster(cluster);
                        return;
                    }
                    else {
                        _this._deactivateCluster();
                    }
                }
            });
        };

Thank you.

**Comment by nickcam** [comment]
You shouldn't need to do this manually, it should be working already.

I feel like I need to reiterate this - the easiest way to troubleshoot these things for yourself and for me to help if needed is to set up a demo that reproduces the problem on stackblitz (for angular apps), or plunkr, or codepen or somewhere else!

In the process of setting up this demo the chances are you'll find the answer to the problem anyway.
