### ISSUE TITLE
Improve the documentation on how to run and integrate this Layer

### ISSUE THREAD

**Issue by davidpelayo** [nickcam/FlareClusterLayer#48]
It would be nice to have, within the README, a quick example of how we can use this layer easily in our ArcGIS projects, so that in a quick glance you'd get the idea of how to start using it.

Due to my recent PR opened (#47), I think a section with requirements and how to start the project would be nice too. In my case, I didn't have the `http-server` required dependency for running the `npm run server` script.

**Comment by nickcam** [comment]
I agree the readme is pretty light on. Should also probably make an npm package so it's easier to integrate.  I'll look at rewording the readme as a start.

To get it running locally you should just need to run:
`npm install`

And then :
`npm start`

Installing the dependencies first should include everything you need to run it. The http-server script is erroneous I think and should be removed.
