### ISSUE TITLE
recreating the clusters in v4.11 is not showing graphics

### ISSUE THREAD

**Issue by pyalam** [nickcam/FlareClusterLayer#49]
Hi nick,

In v4.11 scene view when i tries to recreate the cluster by removing all the graphics and adding them back is not working.The graphics are not adding .unless i zoom in and zoom out then the graphic is coming back to the map.

**Comment by davidpelayo** [comment]
Hi @pyalam, could you please share more details or even a not working version to inspect it?
Which branch code are you using to do so?

**Comment by nickcam** [comment]
Hi @pyalam, sounds like you just need to call `draw()` on the layer after you add the graphics back in. Hard to tell without an example or code snippet though.
