### ISSUE TITLE
Print Cluster Layer with the Esri 4.x Api Print Widget

### ISSUE THREAD

**Issue by Csmith246** [nickcam/FlareClusterLayer#51]
Has anyone had any luck getting the Cluster layer to appear in the pdf print-out that is produced by the Esri api's [Print Widget](https://developers.arcgis.com/javascript/latest/sample-code/widgets-print/index.html)? Currently, the Cluster layer does not show up at all in the pdf print-out.

Does anyone know what it would take to be able to get this to work?

Thanks!

**Comment by nickcam** [comment]
Sorry mate, haven't looked at integrating with the print widget. Maybe when time permits I'll take a look, or someone else may be able to help out.
