### ISSUE TITLE
Show popup when clicking on an individual clustered graphic

### ISSUE THREAD

**Issue by slead** [nickcam/FlareClusterLayer#52]
I've just come across this awesome repo (I can't believe it still isn't core functionality!) and have only looked your demo so far, not the raw code.

When clicking on a cluster icon, the individual markers in that cluster are shown, and when hovering over an individual marker you see its tooltip ("Red Rock" in this example):

![Screen Shot 2019-07-05 at 7 39 48 pm](https://user-images.githubusercontent.com/133596/60713589-bc82b100-9f5c-11e9-8081-913406687ca8.png)

I was hoping to see a popup when I click on the Red Rock graphic, similar to that seen when you click on a non-clustered graphic:

![Screen Shot 2019-07-05 at 7 42 37 pm](https://user-images.githubusercontent.com/133596/60713843-200cde80-9f5d-11e9-98c4-16f58a94732d.png)

Is it possible to show the full popup when clicking on a clustered graphic? Thanks

**Comment by nickcam** [comment]
Hey man, yeah I'm pretty sure it is possible to do. Didn't do it before as the flare graphics may also represent multiple points and the graphics are temporary. They get fully destroyed when the cluster is deactivated.

I'm doing some work on this again to make it work with v4.12, so I'll take a look at implementing this while I'm in there. Can't give a time frame though sorry.

**Comment by roy0633** [comment]
@nickcam thank you for updating to the latest version...
If I make an interesting online system, I will share it with you first.

**Comment by basisbit** [comment]
Other mouse-events like mouse-scrolling (probably for the same reason) also don't work. You can reproduce this by opening the `https://flareclusterlayer.azurewebsites.net/index_v4.html` sample, zooming in a bit on Melbourne, Australia so that lots of screen space if occupied by the bubbles/circles and then try to zoom in/out on the map using mouse scrolling.

**Comment by nickcam** [comment]
Yeah from memory all mouse (pointer) events are disabled over the cluster graphics. There was a good reason for this but I can't remember what is was right now. Will have to take a look when I get a chance.

**Comment by apaleja** [comment]
@nickcam +1 for this. I also would like to show popup similar to [ArcGIS 3.x Implementation](https://developers.arcgis.com/javascript/3/samples/layers_point_clustering/) Can you give some pointers, how to do that ? I will see if I can make required changes.

**Comment by nickcam** [comment]
Finally got around to looking at this. The pointer events are only disabled over the text svg elements, so a click event on the flares works fine. 

I added an event emitter to the layer that will emit an event with a Flare object as the argument. Subscribe to the event on the layer like this - 

```javascript
clusterLayer.on("flare-clicked", function (flare) {
   console.log('flare clicked', flare);
});
```
Any time you click a flare this will then get hit get. All of the data you need to make a popup appear should be in the Flare object that's passed in. If it's a flare representing only one point, then the Flare object will contain a property called `singleData`. This is your data object. You can use the existence of this property to test if you want to create a popup or not.

It's a bit of a cop out not creating the popup within the layer (certainly is easier), but this is bit more flexible so you can anything you want on any flare click.

**Comment by apaleja** [comment]
Hi @nickcam Thank you very much for quick change implementation. I believe this change allows to capture click on Flare of Cluster. I am looking for a solution when `displayFlares: false` and user click on cluster icon. 

Is it possible to emit similar event for cluster click as well ?

**Comment by nickcam** [comment]
Hi @apaleja, no worries - added a cluster-clicked event as well. Use it the same way as the flare-clicked event. 

```javascript
clusterLayer.on("cluster-clicked", function (cluster) {
    console.log('cluster clicked', cluster);
 });
```

**Comment by apaleja** [comment]
@nickcam Thank very much for for quick turn around.
