### ISSUE TITLE
What clustering algorithm do you use?

### ISSUE THREAD

**Issue by zhangluyou** [nickcam/FlareClusterLayer#58]
What clustering algorithm do you use?

**Comment by nickcam** [comment]
Hi @zhangluyou - it's just a custom algorithm. It just creates a grid over the visible extent of the map every time the extent changes. You can configure the size of the cluster grid by setting the clusterRatio property in the options. Each data point is then added to the appropriate cluster grid element as part of a cluster.

Check out these methods in FlareClusterLayer_v4.ts to see how it's done.
[_createClusterGrid()](https://github.com/nickcam/FlareClusterLayer/blob/cdcff7d8ccbf21f8c4ab59f576beb52d4d2264de/typescript/FlareClusterLayer_v4.ts#L599)
[draw()](https://github.com/nickcam/FlareClusterLayer/blob/cdcff7d8ccbf21f8c4ab59f576beb52d4d2264de/typescript/FlareClusterLayer_v4.ts#L295)
