### ISSUE TITLE
Zoom on cluster when clicked

### ISSUE THREAD

**Issue by tannerjt** [nickcam/FlareClusterLayer#59]
I'm trying to determine the best way to zoom to a cluster when clicked on.  I think this is somewhat typical of other cluster libraries.  When a user clicks on the cluster graphic, the view will zoom to the extent of those features.  Is there a recommended route to do this through the library?  My only alternative would be to modify the source directly.

**Comment by nickcam** [comment]
Hi @tannerjt - there's no way to do it at the moment. 
Wouldn't be too hard to add I don't think though.  
- Create a constructor option to toggle the behaviour.
- Create a click/tap event on the cluster graphic.
- Handle the event to zoom the map to the extent of the points within the cluster. 
You're welcome to create a PR if you have a go at it. I'll have a look when I get a chance, not sure when that will be though.
