### ISSUE TITLE
FlareClusterLayer does not work in IE

### ISSUE THREAD

**Issue by gislover100** [nickcam/FlareClusterLayer#6]
It seems FlareClusterLayer does not work in IE, After zoom-in or Pan, Cluster symbols do not show and cluster count remains on map. It works perfect in Chrome.

**Comment by nickcam** [comment]
Hi Mate, which version of IE are you using? I'm pretty sure I only tested it in IE11 to be honest. Just tried it out again quickly and IE11 is fine, but IE10 and below are behaving as you describe. Looks like an easy fix for those though - just need a polyfill for a function...will get to it sometime soon.

This also prompted me to try it in Edge for the first time...and that really doesn't work, getting some totally weird behaviour. Microsoft should just give up on developing browsers, they've always been a major PITA.

Will sort out a fix for Edge soon as well.

**Comment by gislover100** [comment]
Hi Nickcam, Thanks for instant response. I am using IE10, Can you please fix it for IE10 also that would be really good.

when I starts zoom in, all cluster graphic looks OK as expected but it become ugly on end of map zoom-in. 

Thanks

**Comment by nickcam** [comment]
Just committed a change - it should work in IE10 now.

**Comment by gislover100** [comment]
Thanks Nick, It is working like a charm in IE9. I have one more issue. I have two map objects on one html page and I implemented clustering thru your FlareClusterLayer. Clustering rendering fine for both maps. When I hover on cluster graphic on first map object It works fine and shows sub clusters for that graphic but hovering on cluster on second map object does not bring sub clusters graphic. I am getting Sub cluster graphic shape Null each time for second map object. Do you have any idea?

Thanks for your help.

**Comment by nickcam** [comment]
Hi mate, can you create a plunkr or jsfiddle that demos the issue - will make it much easier to sort out.
Thanks,
Nick
