### ISSUE TITLE
Can support the ArcGIS API for JavaScript version 4.13？

### ISSUE THREAD

**Issue by crushjjl** [nickcam/FlareClusterLayer#60]
The version I use is 4.13 （https://js.arcgis.com/4.13/）, and the circle drawn by the mouse hovering appears offset.

**Comment by hellojiangjialin** [comment]
> ### **_`[](url)`_**
![error](https://user-images.githubusercontent.com/22066916/69713012-c17c1300-113e-11ea-8700-7dc9f21be069.png)

**Comment by crushjjl** [comment]
![error](https://user-images.githubusercontent.com/22066916/69713435-7e6e6f80-113f-11ea-947b-62c32dd7e5a8.png)

**Comment by nickcam** [comment]
Hey @hellojiangjialin - just updated it to support v4.13. Give the latest a try.

**Comment by crushjjl** [comment]
@nickcam thank you
