### ISSUE TITLE
Show Popup on Cluster Click

### ISSUE THREAD

**Issue by apaleja** [nickcam/FlareClusterLayer#66]
Thank you very much for keeping this project alive and updated with latest version. I am using this from 3.x implementation. Now I would like to migrate my implementation to 4.x.

One change I made in the 3.x version was enabled popup on cluster click. I would like to do same in 4.x Implementation as well. I have gone though many issues where you have mentioned it is possible. can you guide me , how it can be archived ?

**Comment by nickcam** [comment]
Hi @apaleja, I saw your comment on the other issue. I just haven't had a chance to have a look yet sorry. I'll find some time in the  next couple of days and comment back on this issue.

**Comment by apaleja** [comment]
@nickcam It will be really helpful. Before I start working on new implementation using 4.x I just want to make sure It is possible.

**Comment by nickcam** [comment]
Added a comment to [https://github.com/nickcam/FlareClusterLayer/issues/52](https://github.com/nickcam/FlareClusterLayer/issues/52). Can track this there instead.
