### ISSUE TITLE
Unable to load package with ArcGIS Webpack Plugin

### ISSUE THREAD

**Issue by apaleja** [nickcam/FlareClusterLayer#67]
Hi @nickcam , Thank you very much for continuous support for this incredible library. I am trying to use this package with [ArcGIS Webpack plugin](https://github.com/Esri/arcgis-webpack-plugin). but I am getting following error:

```
Uncaught ReferenceError: exports is not defined
    at Module fcl/FlareCluster.js (FlareClusterLayer_v4.ts:1)
    at __webpack_require__ (bootstrap:63)  
...
```

I am trying to load compiled version (javascript) of package using [dojoConfig Method](https://github.com/Esri/esri-loader#configuring-dojo). but this is not working. any guidance will be helpful in such case.

**Comment by nickcam** [comment]
Hi @apaleja - I've never used the webpack loader so can't really help. Your best bet is to raise an issue in that repo and ask them.

One thing that stands out in that error message is the file name - `FlareCluster.js`
```
at Module fcl/FlareCluster.js (FlareClusterLayer_v4.ts:1)
```
Have you defined that incorrectly somewhere - should it actually be looking for FlareClusterLayer.js or FlareClusterLayer_v4.js?

**Comment by apaleja** [comment]
Hi @nickcam Thanks for quick reply.  About the error message :
> One thing that stands out in that error message is the file name - `FlareCluster.js`

I think that is due to sourcemap of compiled version is pointing to `FlareClusterLayer_v4.ts` file ?

**Comment by nickcam** [comment]
Yeah FlareCluster.js seems weird though...it shouldn't be called that I don't think...but maybe webpack is doing something to it??
Anyway, I think you're best bet is to ask in the arcgis webpack repo. I'm not across the details of how it works.

**Comment by apaleja** [comment]
Thanks I've asked https://github.com/Esri/arcgis-webpack-plugin/issues/101 . adding here for future reference.
