### ISSUE TITLE
onhover opens wrong flareCluster when map is not full body

### ISSUE THREAD

**Issue by apaleja** [nickcam/FlareClusterLayer#68]
Hi @nickcam ,

thanks for your cluster extension. I tried to used it in map instance which is not 100% of the body span. I noticed wrong flareCluster is getting activated on mouseover. 

you can try it here. https://rb.gy/ks9b2w it is clone of this repo with just change in height of the container.

**Comment by apaleja** [comment]
Hi @nickcam any pointers where I should be looking at ?

**Comment by nickcam** [comment]
Grab the latest and try it out again, it should work now. Had to put some manual checks in for screen point when the containers had offsets.
