### ISSUE TITLE
how to use in vue3+vite?

### ISSUE THREAD

**Issue by easy868** [nickcam/FlareClusterLayer#76]
Something went wrong 
![微信截图_20230809140329](https://github.com/nickcam/FlareClusterLayer/assets/22834466/ae214100-e8ff-4f89-bc96-b85f7befdaa8)

    "@arcgis/core": "^4.25.5",

**Comment by nickcam** [comment]
Hi, sorry I've just noticed this issue. I don't think there's any chance it will work on 4.25. Not sure about Vue either. Can be tricky to incorporate the dojo loader into other frameworks.
