### ISSUE TITLE
FireFox 48.0.1 clusterGroup hover position

### ISSUE THREAD

**Issue by JamesRMartin** [nickcam/FlareClusterLayer#8]
When hovering over a clusterGroup the position shifts away from center. I have not had a chance to look at the code behind.  Any quick idea?

The clusterArea looks like it originates from the center of the view, and then shifts/moves to the correct ending position, and the clusterGroup starts at the correct position and then shifts/moves away from the original position the same direction as the clusterArea is shifting.

See attached image.
![clustergroupposition](https://cloud.githubusercontent.com/assets/3729251/18102776/05f3da6a-6eb1-11e6-97cb-e57ad9c74eef.png)

Thanks!

**Comment by nickcam** [comment]
Hi @JamesRMartin,

Sorry can't think of anything off the top of my head...haven't had a chance to test it in that version of firefox...only tested it in an older version. When I can get 48 installed I'll have a look and get back to you.

Thanks,
Nick

**Comment by nickcam** [comment]
Hi @JamesRMartin,

Had a look at this and just committed some fixes...well fixes being removing the scaling animations from Firefox. The css property origin-transform is a bit of a moving target by the looks of it...its implemented differently in firefox and chrome and possibly other browsers. 

Added some notes to index_v4.html and the readme. They should explain what's going on.

**Comment by JamesRMartin** [comment]
@nickcam Awesome!  That works.  Thanks for looking into that, and getting a working fix for the moving target.

Cheers!
