### ISSUE TITLE
4.1 support

### ISSUE THREAD

**Issue by MarcBate** [nickcam/FlareClusterLayer#9]
Can you add support for v4.1 of the Esri JS API?

**Comment by nickcam** [comment]
Hi @MarcBate. I've had a quick look at upgrading to 4.1. Unfortunately - as you may have noticed if you tried to upgrade as well - it seems you can no longer inherit from esri classes in typescript just using a simple extends statement on the custom class as you could in 4.0. 

Something to do with changes they've made to the accessor class and how it's implemented/inherited in their classes. That's all I've had to time to figure out for now...think I'll need to dig into the transpiled javascript and compare it to some samples esri has for creating custom classes, although I couldn't find any samples for 4.1 - do you know of any? Also might just hit up esri support or forums to see if they can let me know how to get around it.

That's the first hurdle anyway, there'll no doubt be other issues once that's been sorted out.  I need to upgrade to 4.1 for one of my projects so it's on my radar...when that can be done I don't know though, sorry. If you manage to work it out please let me know.

**Comment by nickcam** [comment]
Look at supporting upgrade for 4.1. Might be an all or nothing upgrade as far v 4.x is concerned though. I don't think 4.0 and 4.1 will work together in one code base...could create two separate versions for 4.0 and 4.1. Keep 4.0 in a branch and hopefully upgrade to 4.1 support in master.

**Comment by nickcam** [comment]
now upgraded for 4.1.
